apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-b
  namespace: default
spec:
  encryptedData:
    # It's a very very secret message... you cannot read it!
    APPB_VERYSECRETMESSAGE: AgBB7rWNoVkrb852krBnZvLsXDQUJxNAKXEmCTMRivma9AHUb67q+4uiLuQ7Fd/GjzkrG/TFuusE0NF7s8IzywGaEKyjp8MEr+DuGFMCSfYse3JU7T/RgG/x/BB7czCUCXNPwF7Uw+nN6zwamMUjDC1I8gJNyzjGN4B/1oQupBEfacUoquNmnkHAYIXphlpidTDuwHoKAtao3D89l0wj+pg8Pm/av/VkLPYxFr1c8S7CyH97aVrsBuV04DqoNud2YrKcvjqFygh3+eGUYacxD7rSyzs4Yqmcgzijt7HEIsLkhRpDcSLm4HKcNmF8JlEkxgEsodk3GV11Gji0WQhGjL5xc8wyaPOdD8K+bn6w3hTkt2JYLDM3ZEYc70Py1porsqGRzXurv1tKhRvjLvsnpNTRpnPu6zoO0dEEFmvvKIueE6GSHWXNMW3CwzsZhoYZ8yy7D7ncHhA8eJrIcl2rGPt/p/d1KqKovEaaMW/YVEyFJQqPajXwi1NrKwnFz1T9XCR/s1SSSqnG0eLtrsGSxbnWIRcgPVv3uoHW3SS0mUipVueA6pD6eMR+CfAvz/BoCjFHRoYDMu9rszmiiTtGGT69BIcerP90u8ZjufcJ80eWSwdKdWX/YrhpoJgTVj3ozOiy9HW+Ck8RH0CRxr0jf1KIHA6YuTXwqbjlff93uC603I6MNsqhYeJXGoRt6qTnAhG/jHyc6yvADWzsfyfwGP0ichYmKw==
