apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-b
  namespace: default
spec:
  encryptedData:
    # It's a very very secret message... you cannot read it!
    APPB_VERYSECRETMESSAGE: AgA6VDmVmYnxdZEvRPltULYVONQ/bFJcfUgBm4sl2kBhqHfEJX/kFuTRFQmv9Wg/X+lYsyp3qGy5T65llPmHn78HA6RCbHAQ4YYIPrrOueZ8BqE3lrdfFkmOHGDjP9g6E4WsUBDbyeOJ6YSlzRkE7IKk+5tCh2c4x/8tTyR+WmXcFCm8p2AzYNMMUGUi9KJYfvPXyJTzO0GlC9Fy5VM3fF8W0JKGuv05DtNf9b9GTr6UZJaTKgZlMjRck3Sdud7D5GKVZktB+uID+is+2PDOknOoY3On28QDdxs53z/Sin9fP8R/+VLUI321pyMjNOexCMlz3IpxhU7o+wDH16CfHzpYjapxuHMjk50HAURlweAtVxGeFsheb6/5mAN+4YvtnAcEoR9vOOgoY0F61SJlK+AQrtpURk+zGRg8uwGTpADbSb6devPIngXXSUIi6K66JZZuNS5S2eF3KhP8NPLzKYxs59cxsAda6oxC6HOlHQS6OZFwUcaBExLKWk4mXzUf71eYVRgZh4EY4vhnRvsyIs3bb0sxghG3FOnTobxyX6LUAvQfHWCzIHjAFal1GenAOkU9Rf9HFeX3I8oIToLCunyqugZqofbr2TKgH2x3dr11viDoEW4n6Vjjo3lCMH0/UQ3i6S9Bd/9SsZ1GA5tQ/SozZ2UzsTKRCQx+z/mkJ/21yWLytjvgJ3noC5uFk+W7Ft5+sDfksRYMmQA7g/oGzKgV8HTtAt4dNtL3oFz3
